# Generated by Django 2.0 on 2018-08-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['created', 'name']},
        ),
        migrations.AddField(
            model_name='attribute',
            name='content_types',
            field=models.ManyToManyField(blank=True, related_name='eav_attributes', to='contenttypes.ContentType', verbose_name='content types'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='contenttypes.ContentType', verbose_name='content types'),
        ),
    ]
