# Generated by Django 2.0 on 2018-08-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0002_auto_20180824_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['created', 'name']},
        ),
    ]
