# Generated by Django 2.0 on 2018-08-24 13:34

from django.db import migrations


def copy_content_type(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Attribute = apps.get_model('eav', 'Attribute')
    for attr in Attribute.objects.all():
        if attr.content_type:
            attr.content_types.add(attr.content_type)


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0002_auto_20180824_2334'),
    ]

    operations = [
        migrations.RunPython(copy_content_type),
    ]
