# Generated by Django 2.0 on 2018-08-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0003_auto_20180825_0342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('attribute', 'entity_ct', 'entity_id')},
        ),
    ]
