# Generated by Django 2.0 on 2018-11-01 16:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eav', '0005_auto_20181016_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='size',
            field=models.PositiveSmallIntegerField(default=4, blank=True, choices=[(1, 'Mini'), (2, 'Tiny'), (3, 'Small'), (4, 'Medium'), (6, 'Large'), (8, 'Very large'), (12, 'Full length')], help_text='Size of the data contained. User for proper display of forms.'),
        ),
        migrations.AddField(
            model_name='value',
            name='value_multipolygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='value',
            name='value_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=eav.fields.EavDatatypeField(choices=[('text', 'Text'), ('decimal', 'Decimal'), ('float', 'Float'), ('int', 'Integer'), ('date', 'Date'), ('bool', 'True / False'), ('object', 'Django Object'), ('enum', 'Multiple Choice'), ('point', 'Point'), ('multipolygon', 'Multipolygon')], max_length=7, verbose_name='data type'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=eav.fields.EavSlugField(help_text='Short unique attribute label', unique=True, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('content_type', 'name')},
        ),
    ]
