# Generated by Django 2.0 on 2018-11-02 14:22

from django.db import migrations
import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0006_auto_20181102_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=eav.fields.EavDatatypeField(choices=[('text', 'Text'), ('decimal', 'Decimal'), ('float', 'Float'), ('int', 'Integer'), ('date', 'Date'), ('bool', 'True / False'), ('object', 'Django Object'), ('enum', 'Multiple Choice'), ('point', 'Point'), ('multipolygon', 'Multipolygon')], max_length=12, verbose_name='data type'),
        ),
    ]
